! ================================================================================
! Notice : Copyright (C) 2017, Devuna
!          Distributed under the MIT License (https://opensource.org/licenses/MIT)
!
!    This file is part of Devuna-Common (https://github.com/Devuna/Devuna-Common)
!
!    Devuna-Common is free software: you can redistribute it and/or modify
!    it under the terms of the MIT License as published by
!    the Open Source Initiative.
!
!    Devuna-Common is distributed in the hope that it will be useful,
!    but WITHOUT ANY WARRANTY; without even the implied warranty of
!    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
!    MIT License for more details.
!
!    You should have received a copy of the MIT License
!    along with Devuna-Common.  If not, see <https://opensource.org/licenses/MIT>.
! ================================================================================

DEFAULTWINDOWCOLOR          EQUATE(0C08080H)
DEFAULTBROWSECOLOR          EQUATE(0C08080H)
DEFAULTFORMCOLOR            EQUATE(0C08080H)
DEFAULTPANELCOLOR           EQUATE(0DDBBBBH)
DEFAULTSHEETCOLOR           EQUATE(0DDBBBBH)
DEFAULTPROMPTCOLOR          EQUATE(COLOR:NONE)
DEFAULTSTRINGCOLOR          EQUATE(COLOR:NONE)
DEFAULTBACKCOLOR            EQUATE(COLOR:WHITE)
DEFAULTBACKSELECTEDCOLOR    EQUATE(COLOR:NONE)
DEFAULTTEXTCOLOR            EQUATE(COLOR:NONE)
DEFAULTTEXTSELECTEDCOLOR    EQUATE(COLOR:NONE)
