ResultQueueType      QUEUE,TYPE
Path                   CSTRING(261)
Filename               CSTRING(261)
szExtension            CSTRING(MAXEXT+1)
LineNo                 LONG
ProcedureName          CSTRING(256)
Text                   CSTRING(1025)
SortName               CSTRING(261)
szSection              CSTRING(5)
Position               LONG
DeleteInstance         LONG
FileDate               LONG
FileTime               LONG
                     END
                     
SearchQueueType      QUEUE,TYPE
tabNumber                  LONG
bMatchPatternStartOfLine   BOOL
bMatchPatternEndOfLine     BOOL
bUseRegularExpressions     BOOL
bSearchSubdirectories      BOOL
nLevels                    BYTE
nCurrentLevel              BYTE
bCaseSensitive             BOOL
bExactMatch                BOOL
bExcludeMatch              BOOL
bExcludeComments           BOOL
!bIncludeBinary             BOOL
bSearchPressed             BOOL
szPattern                  CSTRING(1025)
szSearchPath               CSTRING(1025)
szFileMask                 CSTRING(256)
szMatchesFound             CSTRING(256)
ResultQueue                &ResultQueueType
UndoQueue                  &ResultQueueType
feqSearchProgress          LONG
lPointer                   LONG
bFilenamesOnly             BOOL
bFileListFromFile          BOOL
szFileListFilename         CSTRING(261)
bSearchStringsFromFile     BOOL
szSearchStringFilename     CSTRING(261)
szPropertyFile             CSTRING(33)
szExcludeMask              CSTRING(256)
szListBoxFormat            CSTRING(256)
FindGroup                  LIKE(FindGrp)
szReplaceWith              LIKE(FindGrp.What)
                     END                      
                     
tqSearchQueue             QUEUE,TYPE
tabNumber                  LONG
bMatchPatternStartOfLine   BOOL
bMatchPatternEndOfLine     BOOL
bUseRegularExpressions     BOOL
bSearchSubdirectories      BOOL
nLevels                    BYTE
nCurrentLevel              BYTE
bCaseSensitive             BOOL
bExactMatch                BOOL
bExcludeMatch              BOOL
bExcludeComments           BOOL
!bIncludeBinary             BOOL
bSearchPressed             BOOL
szPattern                  CSTRING(1025)
szSearchPath               CSTRING(1025)
szFileMask                 CSTRING(256)
szMatchesFound             CSTRING(256)
ResultQueue                &ResultQueueType
UndoQueue                  &ResultQueueType
feqSearchProgress          LONG
lPointer                   LONG
bFilenamesOnly             BOOL
bFileListFromFile          BOOL
szFileListFilename         CSTRING(261)
bSearchStringsFromFile     BOOL
szSearchStringFilename     CSTRING(261)
szPropertyFile             CSTRING(33)
szExcludeMask              CSTRING(256)
szListBoxFormat            CSTRING(256)
FindGroup                  LIKE(FindGrp)
szReplaceWith              LIKE(FindGrp.What)
                        END
                        
FindStrOptionsGroupType    GROUP,TYPE
tabNumber                     LONG
bMatchPatternStartOfLine      BOOL
bMatchPatternEndOfLine        BOOL
bUseRegularExpressions        BOOL
bSearchSubdirectories         BOOL
nLevels                       BYTE
nCurrentLevel                 BYTE
bCaseSensitive                BOOL
bExactMatch                   BOOL
bExcludeMatch                 BOOL
bExcludeComments              BOOL
bSearchPressed                BOOL
szPattern                     CSTRING(1025)
szSearchPath                  CSTRING(1025)
szFileMask                    CSTRING(256)
szMatchesFound                CSTRING(256)
ResultQueue                   &ResultQueueType
UndoQueue                     &ResultQueueType
feqSearchProgress             LONG
lPointer                      LONG
bFilenamesOnly                BOOL
bFileListFromFile             BOOL
szFileListFilename            CSTRING(261)
bSearchStringsFromFile        BOOL
szSearchStringFilename        CSTRING(261)
szPropertyFile                CSTRING(33)
szExcludeMask                 CSTRING(256)
szListBoxFormat               CSTRING(256)
FindGroup                     LIKE(FindGrp)
szReplaceWith                 LIKE(FindGrp.What)
                           END                        